### ISSUE TITLE
Recipient has single email add.

### ISSUE THREAD

**Issue by samrocks1011** [Supme/smtpSender#2]
@Supme   How can I send to multiple recipients using your code?

**Comment by Supme** [comment]
Now it's just only one by one. The builder does not support multi to, cc and bcc.

**Comment by Supme** [comment]
Many recipients in one email will not give a correct server response about delivery. This library was developed with an emphasis on mass mailings. But it is possible to think about adding the possibility of several "to" in the builder.

**Comment by samrocks1011** [comment]
@Supme  Thanks Closing the issue.
